### ISSUE TITLE
Mark all links that open in a new window

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/opentree#611]
Use a typical icon for these. Maybe an easy fix using CSS, something like:
```css
a[target] {
    padding-right: 20px;
    background-image: link-opens-new-window.png
}
```
